name: Deploy Redis Container to Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Redis to Lightsail
    runs-on: ubuntu-latest
    environment: aws_cicd

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.LIGHTSAIL_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH and run Redis container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.LIGHTSAIL_PORT }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            echo "🛑 Stopping existing Redis container if exists..."
            docker stop redis_server || true
            docker rm redis_server || true

            echo "📥 Pulling Redis 6 image..."
            docker pull redis:6

            echo "🚀 Running Redis 6 container..."
            docker run -d \
              --name redis_server \
              -p 6379:6379 \
              --memory="512m" \
              redis:6 \
              redis-server --save "" --appendonly no

            echo "✅ Redis 6 is running on port 6379"
          EOF
