name: Deploy Redis Container to Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Redis to Lightsail
    runs-on: ubuntu-latest
    environment: aws_cicd

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.LIGHTSAIL_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH and run Redis container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p ${{ secrets.LIGHTSAIL_PORT }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            echo "🛑 Stopping existing Redis container if exists..."
            sudo docker stop tradurs.redis || true
            sudo docker rm tradurs.redis || true

            echo "📥 Pulling Redis 6 image..."
            sudo docker pull redis:6

            echo "🚀 Running Redis 6 container..."
            sudo docker run -d \
              --restart always \
              --cpuset-cpus="1" \
              --cpu-shares=1024 \
              --memory="512m" \
              --publish 6379:6379 \
              --network tradurs-network \
              --name tradurs.redis \
              redis:6 \
              redis-server --save "" --appendonly no
            sudo docker system prune -f
            sudo docker buildx prune -f

            echo "✅ Redis 6 is running on port 6379"
          EOF
